<?php

namespace Container4hD887Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QntVEOnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QntVEOn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QntVEOn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'recipeEntity' => ['privates', '.errored..service_locator.QntVEOn.App\\Entity\\Recipe', NULL, 'Cannot autowire service ".service_locator.QntVEOn": it needs an instance of "App\\Entity\\Recipe" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\RecipeRepository', 'getRecipeRepositoryService', true],
        ], [
            'manager' => '?',
            'recipeEntity' => 'App\\Entity\\Recipe',
            'repository' => 'App\\Repository\\RecipeRepository',
        ]);
    }
}
