<?php

namespace ContainerHIPZZba;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZKQAa_DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zKQAa.D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zKQAa.D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'userEntity' => ['privates', '.errored..service_locator.zKQAa.D.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.zKQAa.D": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'hasher' => '?',
            'manager' => '?',
            'repository' => 'App\\Repository\\UserRepository',
            'userEntity' => 'App\\Entity\\User',
        ]);
    }
}
