<?php

namespace ContainerHIPZZba;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MX7WV4FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MX7WV4F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MX7WV4F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BlogController::article' => ['privates', '.service_locator.XqCCpgA', 'get_ServiceLocator_XqCCpgAService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.FInvVvw', 'get_ServiceLocator_FInvVvwService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.go7IyjU', 'get_ServiceLocator_Go7IyjUService', true],
            'App\\Controller\\IngredientController::delete' => ['privates', '.service_locator.ZmyC7gC', 'get_ServiceLocator_ZmyC7gCService', true],
            'App\\Controller\\IngredientController::edit' => ['privates', '.service_locator.EeqUE6k', 'get_ServiceLocator_EeqUE6kService', true],
            'App\\Controller\\IngredientController::index' => ['privates', '.service_locator.cwiUHKK', 'get_ServiceLocator_CwiUHKKService', true],
            'App\\Controller\\IngredientController::new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\RecipeController::delete' => ['privates', '.service_locator.ieGI99y', 'get_ServiceLocator_IeGI99yService', true],
            'App\\Controller\\RecipeController::edit' => ['privates', '.service_locator.QntVEOn', 'get_ServiceLocator_QntVEOnService', true],
            'App\\Controller\\RecipeController::index' => ['privates', '.service_locator.pLEVluA', 'get_ServiceLocator_PLEVluAService', true],
            'App\\Controller\\RecipeController::indexPublic' => ['privates', '.service_locator.9b1ZW6g', 'get_ServiceLocator_9b1ZW6gService', true],
            'App\\Controller\\RecipeController::new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\RecipeController::show' => ['privates', '.service_locator.m_7auvL', 'get_ServiceLocator_M7auvLService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.zKQAa.D', 'get_ServiceLocator_ZKQAa_DService', true],
            'App\\Controller\\UserController::editPassword' => ['privates', '.service_locator.cOXYTDK', 'get_ServiceLocator_COXYTDKService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BlogController:article' => ['privates', '.service_locator.XqCCpgA', 'get_ServiceLocator_XqCCpgAService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.FInvVvw', 'get_ServiceLocator_FInvVvwService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.go7IyjU', 'get_ServiceLocator_Go7IyjUService', true],
            'App\\Controller\\IngredientController:delete' => ['privates', '.service_locator.ZmyC7gC', 'get_ServiceLocator_ZmyC7gCService', true],
            'App\\Controller\\IngredientController:edit' => ['privates', '.service_locator.EeqUE6k', 'get_ServiceLocator_EeqUE6kService', true],
            'App\\Controller\\IngredientController:index' => ['privates', '.service_locator.cwiUHKK', 'get_ServiceLocator_CwiUHKKService', true],
            'App\\Controller\\IngredientController:new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\RecipeController:delete' => ['privates', '.service_locator.ieGI99y', 'get_ServiceLocator_IeGI99yService', true],
            'App\\Controller\\RecipeController:edit' => ['privates', '.service_locator.QntVEOn', 'get_ServiceLocator_QntVEOnService', true],
            'App\\Controller\\RecipeController:index' => ['privates', '.service_locator.pLEVluA', 'get_ServiceLocator_PLEVluAService', true],
            'App\\Controller\\RecipeController:indexPublic' => ['privates', '.service_locator.9b1ZW6g', 'get_ServiceLocator_9b1ZW6gService', true],
            'App\\Controller\\RecipeController:new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\RecipeController:show' => ['privates', '.service_locator.m_7auvL', 'get_ServiceLocator_M7auvLService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.zKQAa.D', 'get_ServiceLocator_ZKQAa_DService', true],
            'App\\Controller\\UserController:editPassword' => ['privates', '.service_locator.cOXYTDK', 'get_ServiceLocator_COXYTDKService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BlogController::article' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\IngredientController::delete' => '?',
            'App\\Controller\\IngredientController::edit' => '?',
            'App\\Controller\\IngredientController::index' => '?',
            'App\\Controller\\IngredientController::new' => '?',
            'App\\Controller\\RecipeController::delete' => '?',
            'App\\Controller\\RecipeController::edit' => '?',
            'App\\Controller\\RecipeController::index' => '?',
            'App\\Controller\\RecipeController::indexPublic' => '?',
            'App\\Controller\\RecipeController::new' => '?',
            'App\\Controller\\RecipeController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::editPassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BlogController:article' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\IngredientController:delete' => '?',
            'App\\Controller\\IngredientController:edit' => '?',
            'App\\Controller\\IngredientController:index' => '?',
            'App\\Controller\\IngredientController:new' => '?',
            'App\\Controller\\RecipeController:delete' => '?',
            'App\\Controller\\RecipeController:edit' => '?',
            'App\\Controller\\RecipeController:index' => '?',
            'App\\Controller\\RecipeController:indexPublic' => '?',
            'App\\Controller\\RecipeController:new' => '?',
            'App\\Controller\\RecipeController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:editPassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
