<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHIPZZba\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHIPZZba/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHIPZZba.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHIPZZba\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHIPZZba\App_KernelDevDebugContainer([
    'container.build_hash' => 'HIPZZba',
    'container.build_id' => '92674e2a',
    'container.build_time' => 1694783467,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHIPZZba');
